@echo off
echo Installing dependencies...
call npm install
echo Building the project...
call npm run build
echo Deploying to GitHub Pages...
call npm run deploy
echo Done! Your site should be live at https://fauzanjavid.github.io/disaster-simulator 