@echo off
echo Initializing Git repository...
git init
echo Adding files...
git add .
echo Creating initial commit...
git commit -m "Initial commit: Disaster Simulator with user authentication"
echo Adding remote repository...
git remote add origin https://github.com/FauzanJavid/disaster-simulator.git
echo Pushing to GitHub...
git push -u origin main
echo Done! 