@echo off
echo Cleaning previous build...
rmdir /s /q build
echo Installing dependencies...
call npm install
echo Building the application...
call npm run build
echo Starting the application...
call npm start 